#################################
# GitHub Dependabot Config info #
#################################
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  # Maintain dependencies for js with npm
  - package-ecosystem: "npm"
    directory: "/mega-linter-runner"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/.automation/test/repository_grype/bad/"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "minimist"
      - dependency-name: "chalk/ansi-regex"
      - dependency-name: "*"

  # Maintain dependencies for ruby with bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for python with pip
  - package-ecosystem: "pip"
    directory: "/.config/python/dev/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/megalinter"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
