site_name: Mega-Linter
site_url: https://nvuillam.github.io/mega-linter/
repo_url: https://github.com/nvuillam/mega-linter
edit_uri: tree/master/docs
site_author: Nicolas Vuillamy
site_description: Mega-Linter documentation
copyright: Copyright &copy; 2020 <a href="https://github.com/nvuillam">Nicolas Vuillamy</a>
theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - "Home": "index.md"
  - "Quick Start": "#quick-start"
  - "Linters":
      - "Languages": "#languages"
      - "Formats": "#formats"
      - "Tooling formats": "#tooling-formats"
  - "Installation": "#installation"
  - "Configuration": "#configuration"
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
extra_css:
  - stylesheets/extra.css
