
title = "gitleaks config"

[allowlist]
    description = "Allowlisted files"
    paths = [
    '''.automation/test''',
    '''megalinter-reports''',
    '''.github/linters''',
    '''node_modules''',
    '''.mypy_cache''',
    '''(.*?)gitleaks\.toml$''',
    '''(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$''',
    '''(go.mod|go.sum)$''']
