---
#########################
#########################
## Deploy Docker Image Flavors ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
name: "Build & Deploy - PROD Flavors"
on:
  push:
    branches:
      - "master"
      - "FlavoredMegaLinters"
    paths:
      - "Dockerfile"
      - "megalinter/**"
      - "flavors/**"
      - "**/linter-versions.json"

###############
# Set the Job #
###############
jobs:
  # Skip checks: https://github.com/fkirc/skip-duplicate-actions#option-3-cancellation-only
  skip_checks:
    name: Skip checks
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

  build:
    # Name the Job
    name: Deploy Docker Image - PROD - Flavors
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # flavors-start
        flavor:
          [
            "dart",
            "documentation",
            "dotnet",
            "go",
            "java",
            "javascript",
            "php",
            "python",
            "ruby",
            "rust",
            "scala",
            "terraform",
          ]
# flavors-end
    # Only run this on the main repo
    if: github.repository == 'nvuillam/mega-linter'
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      #####################
      # Run Deploy script #
      #####################
      - name: Deploy latest image to DockerHub
        env:
          # Set the Env Vars
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_REPO: nvuillam/mega-linter-${{ matrix.flavor }}
          IMAGE_VERSION: latest
          DOCKERFILE_PATH: flavors/${{ matrix.flavor }}/Dockerfile
          REGISTRY: Docker
        shell: bash
        run: .automation/upload-docker.sh
