---
#########################
#########################
## Deploy Docker Image Flavors ##
#########################
#########################
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to main #
#######################################
name: "Build & Deploy - BETA linters"
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "Dockerfile"
      - "**/Dockerfile"
      - "flavors/**"
      - "megalinter/**"
      - "mega-linter-runner/**"
      - "**/linter-versions.json"
      - "TEMPLATES/**"
      - ".trivyignore"
      - "**/*.sh"
      - "**/*.py"
      - "**/sh/**"

###############
# Set the Job #
###############
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  prepare:
    name: Prepare matrix
    runs-on: ubuntu-latest  
    steps:

    - name: Build unique image name for beta
      shell: bash
      run: echo "UNIQUE_DOCKER_IMAGE_NAME=$(echo beta_$(date '+%Y%m%d-%H%M'))" >> $GITHUB_ENV

    - name: Prepare result is ${{ env.UNIQUE_DOCKER_IMAGE_NAME }}
      shell: bash
      run: echo ${{ env.UNIQUE_DOCKER_IMAGE_NAME }}  

    outputs:
      unique_docker_image_name: "${{ env.UNIQUE_DOCKER_IMAGE_NAME }}"  

  build:
    needs: prepare
    # Name the Job
    name: Deploy Docker Image - Beta - Linters
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # linters-start
        linter:
          [
            "ansible_ansible_lint",
            "bash_shellcheck",
            "cloudformation_cfn_lint",
            "dockerfile_hadolint",
            "go_revive",
            "groovy_npm_groovy_lint",
            "java_checkstyle",
            "java_pmd",
            "javascript_es",
            "json_eslint_plugin_jsonc",
            "jsx_eslint",
            "kotlin_ktlint",
            "php_psalm",
            "python_bandit",
            "repository_checkov",
            "repository_devskim",
            "repository_dustilock",
            "repository_gitleaks",
            "repository_secretlint",
            "repository_semgrep",
            "repository_syft",
            "repository_trivy",
            "terraform_tflint",
            "terraform_terrascan",
            "terraform_checkov",
            "tsx_eslint",
            "typescript_es",
          ]
# linters-end
    # Only run this on the main repo
    if: github.repository == 'oxsecurity/megalinter' && !contains(github.event.head_commit.message, 'skip deploy')
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: linters/${{ matrix.linter }}/Dockerfile
          platforms: linux/amd64
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
          load: false
          push: true
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: |
            oxsecurity/megalinter-only-${{ matrix.linter }}:beta
            oxsecurity/megalinter-only-${{ matrix.linter }}:{{ needs.prepare.outputs.unique_docker_image_name }}
            ghcr.io/oxsecurity/megalinter-only-${{ matrix.linter }}:beta
            ghcr.io/oxsecurity/megalinter-only-${{ matrix.linter }}:{{ needs.prepare.outputs.unique_docker_image_name }}

      #####################################
      # Run Linter test cases #
      #####################################
      - name: Run Test Cases
        shell: bash
        run: |
          TEST_KEYWORDS_TO_USE_UPPER="${{ matrix.linter }}"
          TEST_KEYWORDS_TO_USE="${TEST_KEYWORDS_TO_USE_UPPER,,}"
          docker run -e TEST_CASE_RUN=true -e OUTPUT_FORMAT=text -e OUTPUT_FOLDER=${GITHUB_SHA} -e OUTPUT_DETAIL=detailed -e GITHUB_SHA=${GITHUB_SHA} -e PAT="${{secrets.PAT}}" -e TEST_KEYWORDS="${TEST_KEYWORDS_TO_USE}" -e MEGALINTER_VOLUME_ROOT="${GITHUB_WORKSPACE}" -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v ${GITHUB_WORKSPACE}:/tmp/lint oxsecurity/megalinter-only-${{ matrix.linter }}:beta
        timeout-minutes: 30

      ##############################################
      # Check Docker image security with Trivy #
      ##############################################
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/oxsecurity/megalinter-only-${{ matrix.linter }}:beta'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          security-checks: vuln
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: 10m0s
