---
#########################
#########################
## Deploy Docker Image ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
on:
  release:
    # Want to run the automation when a release is created
    types: ["created"]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Deploy Docker Image - Release
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Only run on main repo
    if: github.repository == 'nvuillam/mega-linter'
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      ########################################################
      # Publish updated version of mega-linter-runner on NPM #
      ########################################################
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: cd mega-linter-runner && npm install
      - run: cd mega-linter-runner && npm publish || echo "mega-linter-runner not published"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      ###################################
      # Run Deploy script for Dockerhub #
      ###################################
      - name: Deploy Release image to Dockerhub
        env:
          # Set the Env Vars
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_REPO: nvuillam/mega-linter
          IMAGE_VERSION: ${{ github.event.release.tag_name }}
          DOCKERFILE_PATH: Dockerfile
          REGISTRY: Docker
        shell: bash
        run: .automation/upload-docker.sh

      ###################################################
      # Run Deploy script for GitHub Container Registry #
      ###################################################
      - name: Deploy Release image to GitHub Container Registry
        env:
          # Set the Env Vars
          GCR_USERNAME: ${{ secrets.GCR_USERNAME }}
          GCR_TOKEN: ${{ secrets.GCR_PASSWORD }}
          IMAGE_REPO: nvuillam/mega-linter
          IMAGE_VERSION: ${{ github.event.release.tag_name }}
          DOCKERFILE_PATH: Dockerfile
          REGISTRY: GCR
        shell: bash
        run: .automation/upload-docker.sh
