name: help-command
on:
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7:We are only triggering these workflows by users with write access manually, it is expected. 
    # Error was: 
    # The build output cannot be affected by user parameters other than the build entry point and the top-level source location. 
    # GitHub Actions workflow_dispatch inputs MUST be empty. 
    inputs:
      repository:
        description: 'The repository from which the slash command was dispatched'
        required: true
      comment-id:
        description: 'The comment-id of the slash command'
        required: true
      issue-number:
       description: 'The issue number in which the slash command was made'
       required: true
      actor:
       description: 'The user who executed the slash command'
       required: true
  repository_dispatch:
    types: [help-command]
jobs:
  help:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          ## Use token if we want to use a PAT instead of GITHUB_TOKEN, GITHUB_TOKEN acts as github-actions[bot]
          # token: ${{ secrets.GITHUB_TOKEN }}
          ## These are if we want to use repository_dispatch (default)
          # repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          # comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          repository: ${{ github.event.inputs.repository }}
          comment-id: ${{ github.event.inputs.comment-id }}
          issue-number: ${{ github.event.inputs.issue-number }}
          body: |
            > Command | Description
            > --- | ---
            > /build | Updates the Dockerfile, documentation, and other files from the yml descriptors
            > /build [ref=...]| Same as /build, but executes workflow in any branch using the ref named argument. The reference can be a branch, tag, or a commit SHA. This can be useful to test workflows in PR branches before merging.
            > /help | Returns this help message
          reaction-type: hooray